geofmureithi/apalis

README.md
examples/actix-web/Cargo.toml
examples/actix-web/src/main.rs
examples/axum/Cargo.toml
examples/axum/src/main.rs
examples/mysql/Cargo.toml
examples/mysql/src/main.rs
examples/postgres/Cargo.toml
examples/postgres/src/main.rs
examples/prometheus/Cargo.toml
examples/prometheus/src/main.rs
examples/redis/Cargo.toml
examples/redis/src/main.rs
examples/rest-api/Cargo.toml
examples/rest-api/src/main.rs
examples/sentry/Cargo.toml
examples/sentry/src/main.rs
examples/sqlite/Cargo.toml
examples/sqlite/src/main.rs
examples/tracing/Cargo.toml
examples/tracing/src/main.rs
packages/apalis-core/Cargo.toml
packages/apalis-core/src/layers/sentry/mod.rs
packages/apalis-core/src/layers/tracing/mod.rs
packages/apalis-core/src/worker/mod.rs
packages/apalis-core/src/worker/monitor.rs
packages/apalis-sql/src/sqlite.rs
src/lib.rs

Refactor alot of panics

---

examples/redis/src/main.rs
packages/apalis-redis/src/storage.rs

Added JobID to fix missing ack data

---

packages/apalis-core/src/executor.rs
packages/apalis-redis/Cargo.toml
packages/apalis-redis/src/storage.rs

This fixes #49 
Was tested on both tokio and async-std

Fixes Redis reconnection issues

---

examples/basics/src/main.rs
packages/apalis-core/Cargo.toml
packages/apalis-core/src/context.rs
packages/apalis-core/src/lib.rs
src/lib.rs

Related to https://github.com/geofmureithi/apalis/issues/208

fix: Doctests

---

examples/basics/src/main.rs
examples/redis/src/main.rs
packages/apalis-core/src/monitor/mod.rs
packages/apalis-core/src/monitor/shutdown.rs
packages/apalis-core/src/worker/mod.rs

Resolves #253 
This returns the use of a shutdown terminator.
Currently a timeout option is provided but one can use any future.

add: shutdown terminator

---

packages/apalis-sql/src/postgres.rs

Related to #277 & #292 , though no tests yet.

fix: wrong timestamp type for pg

---

Cargo.toml
packages/apalis-core/Cargo.toml
packages/apalis-cron/Cargo.toml
packages/apalis-redis/Cargo.toml
packages/apalis-sql/Cargo.toml

bump: to version 0.5.2

---

Cargo.toml
README.md
benches/storages.rs
examples/actix-web/src/main.rs
examples/axum/src/main.rs
examples/prometheus/src/main.rs
examples/redis-with-msg-pack/Cargo.toml
examples/redis-with-msg-pack/src/main.rs
examples/redis/src/main.rs
examples/sentry/src/main.rs
examples/tracing/src/main.rs
packages/apalis-redis/src/lib.rs
packages/apalis-redis/src/storage.rs
src/lib.rs

Breaking changes.
- `RedisStorage::new` now expects two arguments, connection and config

fix: introduce namespace and codec config

---

Cargo.toml
packages/apalis-core/Cargo.toml
packages/apalis-cron/Cargo.toml
packages/apalis-redis/Cargo.toml
packages/apalis-sql/Cargo.toml

Bump to the first release candidate.

Bump to 0.6.0 rc.1

---

Cargo.toml
examples/redis-mq-example/Cargo.toml
examples/redis-mq-example/src/main.rs
packages/apalis-core/src/memory.rs
packages/apalis-core/src/mq/mod.rs
packages/apalis-redis/src/storage.rs
src/layers/tracing/make_span.rs

Example: add rsmq 

---

examples/redis-mq-example/src/main.rs
packages/apalis-redis/src/storage.rs
packages/apalis-sql/src/postgres.rs

fix: handle unwraps in storages

---

src/layers/retry/mod.rs

Handle 0 retries

---

examples/redis/src/main.rs
packages/apalis-core/src/error.rs
packages/apalis-core/src/layers.rs
packages/apalis-redis/lua/done_job.lua
packages/apalis-redis/lua/kill_job.lua
packages/apalis-redis/lua/retry_job.lua
packages/apalis-redis/src/storage.rs
packages/apalis-sql/src/context.rs
packages/apalis-sql/src/lib.rs
packages/apalis-sql/src/mysql.rs
packages/apalis-sql/src/postgres.rs
packages/apalis-sql/src/sqlite.rs
src/layers/catch_panic/mod.rs

Currently just the status is stored, this PR adds the ability to save the result

Feature: Save results for storages

---

src/layers/retry/mod.rs

fix: handle 0 retries

---

Cargo.toml
examples/redis-deadpool/src/main.rs
examples/redis-mq-example/src/main.rs
examples/redis-with-msg-pack/Cargo.toml
examples/redis-with-msg-pack/src/main.rs
packages/apalis-core/Cargo.toml
packages/apalis-core/src/codec/json.rs
packages/apalis-core/src/lib.rs
packages/apalis-cron/Cargo.toml
packages/apalis-redis/Cargo.toml
packages/apalis-redis/src/lib.rs
packages/apalis-redis/src/storage.rs
packages/apalis-sql/Cargo.toml
packages/apalis-sql/src/lib.rs
packages/apalis-sql/src/mysql.rs
packages/apalis-sql/src/postgres.rs
packages/apalis-sql/src/sqlite.rs

The API for codec was rough on the edges. This standardizes the `Codec` trait and allows for serializing of multiple types.

chore: standardize codec usage

---

Cargo.toml
packages/apalis-core/Cargo.toml
packages/apalis-cron/Cargo.toml
packages/apalis-redis/Cargo.toml
packages/apalis-sql/Cargo.toml

This bumps the version to 0.5.4.
This will possibly be the last release for 0.5

release version 0.5.4

---

Cargo.toml
packages/apalis-core/Cargo.toml
packages/apalis-cron/Cargo.toml
packages/apalis-redis/Cargo.toml
packages/apalis-sql/Cargo.toml

Bump a new release candidate. Mainly adds the Request x Context

bump: to 0.6.0-rc.7

---

.github/workflows/ci.yaml
README.md
src/lib.rs

chore: rename master to main

---

examples/redis-mq-example/src/main.rs

fix: missing redismq missing message_id

---

packages/apalis-redis/lua/get_jobs.lua
packages/apalis-redis/lua/stats.lua
packages/apalis-redis/src/expose.rs
packages/apalis-redis/src/storage.rs

* Move script into a separate lua file
* Pass correct arguments to the script: "active" is actually "pending"
* Iterate over all consumer to count their inflight jobs count

Fix RedisStorage::stats

---

examples/async-std-runtime/src/main.rs
packages/apalis-cron/src/lib.rs

Allows graceful shutdown for cron jobs.

fix: refactor and fix cron hearbeat

---

CHANGELOG.md
packages/apalis-sql/migrations/postgres/20250223193249_fix_get_jobs_conditional.sql
packages/apalis-sql/src/postgres.rs

fix: PostgresStorage get_jobs status conditional

---

CHANGELOG.md
examples/cron/src/main.rs
examples/persisted-cron/src/main.rs
packages/apalis-core/src/request.rs
packages/apalis-cron/src/lib.rs

TODO: handle pipe to backends better

feat: introduce cron context

---

Cargo.toml
packages/apalis-core/Cargo.toml
packages/apalis-cron/Cargo.toml
packages/apalis-redis/Cargo.toml
packages/apalis-sql/Cargo.toml

- This bumps to a new version 0.7.0

bump: to 0.7.0

---

CHANGELOG.md
Cargo.toml
packages/apalis-core/Cargo.toml
packages/apalis-cron/Cargo.toml
packages/apalis-redis/Cargo.toml
packages/apalis-sql/Cargo.toml

bump: to v0.7.1

---

CHANGELOG.md
examples/prometheus/Cargo.toml
examples/prometheus/src/main.rs

The prometheus example needs a small fix in order to work 
After the fix we can get this kind of data : 
```
requests_total{name="email_service::Email",namespace="email_service::Email",status="Err"} 3
requests_total{name="email_service::Email",namespace="email_service::Email",status="Ok"} 7
request_duration_seconds_bucket{name="email_service::Email",namespace="email_service::Email",status="Ok",le="0.005"} 7
request_duration_seconds_bucket{name="email_service::Email",namespace="email_service::Email",status="Ok",le="0.01"} 7
request_duration_seconds_bucket{name="email_service::Email",namespace="email_service::Email",status="Ok",le="0.025"} 7
request_duration_seconds_bucket{name="email_service::Email",namespace="email_service::Email",status="Ok",le="0.05"} 7 …
```

Prometheus Example

---

CHANGELOG.md
Cargo.toml
packages/apalis-core/Cargo.toml
packages/apalis-cron/Cargo.toml
packages/apalis-redis/Cargo.toml
packages/apalis-sql/Cargo.toml

bump: apalis to v0.7.3
