packages/apalis-sql/src/mysql.rs
I found a bug with table name in `mysql.rs`.
In default configuration (`lower_case_table_names=0`) of MySQL on linux, table name are case-sensitive.
The table name managing jobs should be `jobs`, but in some SQL it is referred as `Jobs`.
As a result, this library does not work with such MySQL servers.
With this PR, I modified every occurrence of `Jobs` in SQL statements with `jobs`.
=> s/Job/jobs/ in mysql.rs

.github/workflows/ci.yaml, packages/apalis-sql/Cargo.toml, packages/apalis-sql/src/mysql.rs
Closes #5 
This PR implements missing feature to re-run dead jobs for MySQL backends.
I added unit tests for this feature. The scenario is the following steps. 
1. Push a job
2. Register a worker with `last_seen = (6 minutes ago)`.
3. Pull the job by the worker.
4. Call `heartbeat` with `ReenqueueOrphaned`.
5. Assert that the job status is reset to `Pending`.
1. Push a job
2. Register a worker with `last_seen = (4 minutes ago)`.
3. Pull the job by the worker.
4. Call `heartbeat` with `ReenqueueOrphaned`.
5. Assert that the job status is not changed.
- Extracted method `keep_alive_at(worker_id, last_seen)` from `keep_alive(worker_id)` to improve testability  
- Modified the condition `run_at < NOW()` in `stream_jobs` to `run_at <= NOW()`, because jobs cannot be pulled immediately after …
=> Mysql rerun dead jobs

packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
This PR fixes a bug with killing a job.
In MySQL/Postgres/Sqlite3 backends, `Storage::kill(self, worker_id, job_id)` sets the status to `'Kill'`, which is incompatible to the definition of `JobStatus::Killed`.
https://github.com/geofmureithi/apalis/blob/3cfc8df9a9bcb288ea24c3892e2446c45247b947/packages/apalis-core/src/request.rs#L12-L26
As a result, deserialization of job context will panic while converting `Kill` to `JobState`. https://github.com/geofmureithi/apalis/blob/3cfc8df9a9bcb288ea24c3892e2446c45247b947/packages/apalis-sql/src/from_row.rs#L53
=> s/Kill/Killed/ in storage.kill

.github/workflows/ci.yaml, packages/apalis-sql/src/postgres.rs
Part of #9 
This PR adds `Test Suite with Postgres` action and implements 5 tests for Postgres backend.
- test_consume_last_pushed_job
- test_acknowledge_job
- test_kill_job
- test_heartbeat_renqueueorphaned_pulse_last_seen_6min
- test_heartbeat_renqueueorphaned_pulse_last_seen_4min
I extracted `keep_alive_at(self, worker_id, last_seen)` from `keep_alive(self, worker_id)` to improve testability.
When `keep_alive_at(self, worker_id, last_seen)` is called for `worker_id` already registered, the `last_seen` column of the worker row is updated with `NOW()` (system clock on the Postgres server).
Although this behavior was trivial things, the value of `last_seen` can be different from the current time due to the refactoring. 
Therefore, I changed the updated value to `EXCLUDED.last_seen`, which …
=> Add Integration Tests for Postgres backend

.github/workflows/ci.yaml, packages/apalis-sql/src/mysql.rs
This PR fixes the issue sharing the connection pool on MySQL backend, and adds more tests for MySQL backend.
This PR also contains a bug fix that `lock_at` is not updated when a job is locked. (See `stream_jobs` method)
=> Add more tests for MySQL backend

.github/workflows/cd.yaml, .github/workflows/ci.yaml
#19 
This PR adds a workflow (Continuous delivery) to publish crates to crates.io.
Continuous delivery workflow is triggered by pushing tags to the remote repository.
Tag must be of the form `vX.Y.Z` or `vX.Y.Z-SUFFIX`. 
A tag with suffix means pre-release version and it enables `--dry-run` mode.
Please set `CARGO_REGISTRY_TOKEN` for the authentication token for crates.io.
- `test`
- This job runs several tests defined in `ci.yaml`.
- `publish`
- This job publishes crates (`apalis-core`, `apalis-cron`, `apalis-redis`, `apalis-sql`, and `apalis`) in an appropriate order.
- If there are some inconsistencies between the tag version and a package version (written in `Cargo.toml`), the job fails before pushing the crates.
I have created `v0.3.4-rc10` tag and confirmed that the workflow …
=> add cd.yaml

examples/mysql/Cargo.toml, examples/postgres/Cargo.toml, examples/redis/Cargo.toml, examples/rest-api/Cargo.toml, examples/sentry/Cargo.toml, examples/sqlite/Cargo.toml, examples/tracing/Cargo.toml, packages/apalis-core/Cargo.toml, packages/apalis-cron/Cargo.toml, packages/apalis-redis/Cargo.toml, packages/apalis-sql/Cargo.toml
The transitive time 0.1 dependency gets flagged for its security vulnerabilities. This change to the active features on chrono prevents it.
Before:
```
› cargo tree -e=normal -i=time
time v0.1.43
└── chrono v0.4.23
└── apalis-core v0.3.5 (/Users/rob/Development/forks/apalis/packages/apalis-core)
└── apalis v0.3.5 (/Users/rob/Development/forks/apalis)
```
After:
```
› cargo tree -e=normal -i=time
error: package ID specification `time` did not match any packages
Did you mean `libc`?
```
=> Remove time 0.1 from dependency tree

packages/apalis-core/src/layers/tracing/mod.rs
Allow the usage of traits/defaults struct used for implementation of the TraceLayer.
This is to avoid redefining all layers when creating a "generic" TraceLayer. For example in this case:
```
fn trace_on_req<B>(name: String) -> impl FnMut(&JobRequest<B>, &Span){
move |_, _| {
tracing::event!(Level::DEBUG, "job.start: {}", name);
}
}
fn my_trace_layer<B>() -> TraceLayer<apalis_core::layers::tracing::make_span::DefaultMakeSpan, impl for<'a, 'b> FnMut(&'a apalis::prelude::JobRequest<B>, &'b Span)> {
TraceLayer::new().on_request(trace_on_req::<B>("my_task".into()))
}
```
We have to redefine the MakeSpan function since we don't have access to DefaultMakeSpan.
=> chore: expose traits and defaults struct for TraceLayer

packages/apalis-cron/src/lib.rs
=> fix: add option for timezone

packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
=> add: api to get migrations

packages/apalis-core/src/worker/ready.rs
A potential fix to address issue https://github.com/geofmureithi/apalis/issues/143
Tested with the modified code in the issue.
actix-web example hangs but this may be due to starting the monitor without a signal handler with actix.
=> Address worker shutdown signal propagation

packages/apalis-core/src/context.rs, packages/apalis-core/src/lib.rs, packages/apalis-redis/src/lib.rs, packages/apalis-redis/src/storage.rs, packages/apalis-sql/src/lib.rs, packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
I believe there is also a crate which allows mutually exclusive features, so we could do that instead.
=> fix: Allow cargo build --all-features

packages/apalis-core/src/storage/beats.rs, packages/apalis-core/src/storage/builder.rs, packages/apalis-core/src/storage/mod.rs, packages/apalis-redis/src/storage.rs, packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
The idea is to be able to configure the duration after which a worker is considered as dead in order to reenque orphan jobs. Before this PR this time was fixed to 5 minutes.
=> feat: configurable worker set as dead

packages/apalis-core/src/builder.rs, packages/apalis-core/src/lib.rs, packages/apalis-core/src/storage/builder.rs, packages/apalis-core/src/worker/ready.rs, packages/apalis-redis/src/storage.rs
This PR is a POC that introduce concurrency limitation per worker. 
Instead of consuming & running all tasks in a queue, you can limit the number of fetched and thus concurrent running jobs. As we can found in [celery](https://docs.celeryq.dev/en/stable/userguide/optimizing.html#prefetch-limits) 
@geofmureithi Another way to achieve that is to change the Return of `fn consume` instead of returning `JobStreamResult<T>` we can return `JobStreamResult<Vec<T>>` this way we avoid the need for an extra parameter ie `max_concurrent_jobs`. 
A worker will then fetch at most `buffer_size` jobs and run them directly and wait for all results thanks to `fn join_all`. 
- For short lived jobs you can then configure a high `buffer_size`, note today is theoretically infinite and may cause CPU/memory …
=> feat!: configurable concurrency per worker 

packages/apalis-core/src/mq/builder.rs
0.4.8 update broke Mq WorkerBuilder initialization:
```
|
37 |         WorkerBuilder {
|         ^^^^^^^^^^^^^ missing `max_concurrent_jobs`
```
=> Fixing MQ builder

examples/redis/src/main.rs, src/lib.rs
apalis_redis was already exporting 3 items : 
- connect, RedisStorage & Config
But apalis was re-exporting only: 
- connect & RedisStorage
=> fix: re-export apalis_redis::Config in apalis crate

packages/apalis-sql/src/lib.rs
I wanted to modify the poll interval to be less frequent and saw the fields in the sql config were private, so this just adds some setters.
=> fix: allow sql config values to be modified

packages/apalis-core/Cargo.toml, packages/apalis-core/src/lib.rs
Attempts to resolve #291 and  #301 without a version bump
=> fix: replace async-timer with futures-timer

Cargo.toml, benches/storages.rs, examples/actix-web/src/main.rs, examples/axum/src/main.rs, examples/postgres/src/main.rs, examples/prometheus/src/main.rs, examples/redis-deadpool/Cargo.toml, examples/redis-deadpool/src/main.rs, examples/redis/src/main.rs, examples/sentry/src/main.rs, examples/tracing/src/main.rs, packages/apalis-core/src/builder.rs, packages/apalis-core/src/layers.rs, packages/apalis-core/src/lib.rs, packages/apalis-core/src/memory.rs, packages/apalis-core/src/poller/mod.rs, packages/apalis-core/src/request.rs, packages/apalis-core/src/storage/mod.rs, packages/apalis-core/src/worker/stream.rs, packages/apalis-redis/src/lib.rs, packages/apalis-redis/src/storage.rs, packages/apalis-sql/src/context.rs, packages/apalis-sql/src/lib.rs, packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs, src/lib.rs
Changelog:
- Redis storage doesnt require pool to be clone. Allows use of deadpool-redis among others.
- Namespace is picked by default for `new` methods.
=> Version: 0.6.0-alpha.1

examples/redis/src/main.rs, packages/apalis-core/src/layers.rs, packages/apalis-core/src/monitor/mod.rs, packages/apalis-core/src/worker/mod.rs
Fixes a bug where backend layers were not loaded
=> layer from poller

benches/storages.rs, examples/redis-mq-example/src/main.rs, packages/apalis-core/src/mq/mod.rs
=> Fix: mq example

Cargo.toml, examples/async-std-runtime/src/main.rs, examples/cron/Cargo.toml, examples/cron/src/main.rs, packages/apalis-core/src/builder.rs, packages/apalis-core/src/monitor/mod.rs, packages/apalis-core/src/worker/mod.rs, packages/apalis-cron/Cargo.toml, packages/apalis-cron/src/lib.rs
- standardize cron and include example.
=> feat: standardize cron as backend

Cargo.toml, README.md, examples/basics/Cargo.toml, examples/basics/src/main.rs, src/layers/catch_panic/mod.rs, src/layers/mod.rs
This allows preventing job execution from killing workers and returns an error containing the backtrace
=> Feature: Add a layer that catches panics

packages/apalis-core/src/layers.rs, packages/apalis-redis/src/storage.rs, packages/apalis-sql/Cargo.toml, packages/apalis-sql/src/context.rs, packages/apalis-sql/src/from_row.rs, packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
=> fix: handle attempts in storages

Cargo.toml, examples/sqlite/Cargo.toml, packages/apalis-sql/Cargo.toml
Updates the `sqlx` dependency to `0.8.1` to address the vulnerability described in #401
=> Update sqlx to 0.8.1

.github/workflows/ci.yaml, examples/async-std-runtime/src/main.rs, examples/basics/src/main.rs, examples/mysql/src/main.rs, examples/postgres/src/main.rs, examples/tracing/Cargo.toml, examples/tracing/src/main.rs, packages/apalis-redis/src/storage.rs, src/layers/prometheus/mod.rs, src/layers/retry/mod.rs
fix: tower updates
fix: CI to handle the whole workspace
Fixes #406
=> patch: 0.5.4

packages/apalis-sql/src/mysql.rs
`keep_alive_at` function uses replace to update the worker row and that forces the jobs child rows to be deleted due to their foreign key relationship. This behavior is due MySQL `REPLACE` deletes first a row when duplicated.
Using `INSERT .. ON DUPLICATE KEY` solves the issue. Jobs are not deleted anymore when the `keep_alive_at` runs. Users should be responsible about truncating the jobs table with this approach. Fixes  #48
=> [mysql] prevent cascading deletes on jobs by `keep_alive_at`

examples/fn-args/src/main.rs, packages/apalis-core/src/task/namespace.rs, packages/apalis-core/src/task/task_id.rs, packages/apalis-core/src/worker/mod.rs
Problem: We are missing crucial `FromRequest` impls for:
- TaskId
- Attempt
- Namespace
Also removed `Context<E>`
Solution: Implement `FromRequest` for these Types.
=> fix: apply `FromRequest` for items in `Parts`

packages/apalis-core/src/lib.rs, packages/apalis-core/src/worker/mod.rs, packages/apalis-redis/src/storage.rs, packages/apalis-sql/src/lib.rs, packages/apalis-sql/src/postgres.rs, src/layers/catch_panic/mod.rs, src/layers/prometheus/mod.rs
Problem:
The current worker logic is missing an implementation where the backend provided layer should be added to the service's layer. This is a critical issue that affects all v0.6.0-rc-7 users and they should update as soon as a new release is done.
Solution:
- Add backend layers to service's layer.
- Add worker_consume tests on the storages to prevent regression on this.
Fixes: #419
=> fix:[bug] include backend provided layer in service layers.

Cargo.toml, packages/apalis-core/Cargo.toml, packages/apalis-cron/Cargo.toml, packages/apalis-redis/Cargo.toml, packages/apalis-sql/Cargo.toml
- This includes vital fixes and anyone using rc.7 should update
=> chore: bump to 0.6.0-rc.8

packages/apalis-redis/src/storage.rs
It seems that the initial intention was to clean up done jobs (from the surrounding code also), but the code references dead jobs. It also might make more sense to drop done jobs and keep dead ones for issue analysis.
SQL packages remove "done" jobs with vacuuming also:
```SQL
Delete from jobs where status='Done'
```
=> fix: target done jobs with vacuuming instead of dead jobs

packages/apalis-sql/src/context.rs, packages/apalis-sql/src/from_row.rs, packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
So that a custom number of attempts can be configured:
```rust
let mut ctx = SqlContext::new();
ctx.set_max_attempts(2);
let req = Request::new_with_ctx(job, ctx);
storage.push_request(req).await.unwrap();
```
While the default is still to try up to 25 times:
```rust
storage.push(job).await.unwrap();
```
Right now, the default will be used, no matter what the request contains.
=> fix: apply max_attempts set via SqlContext

packages/apalis-sql/src/lib.rs
Making sqlx accessible to users of apalis without requiring them to explicitly add it as a dependency.
One of my use cases is a custom vacuum implementation that runs SQL using the already accessible `SqlitePool`.
=> feat: re-export sqlx

packages/apalis-redis/src/storage.rs, packages/apalis-sql/src/lib.rs, packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
=> feat: add recovery of abandoned jobs to backend heartbeats

examples/redis-mq-example/src/main.rs, packages/apalis-core/src/lib.rs, packages/apalis-core/src/memory.rs, packages/apalis-core/src/request.rs, packages/apalis-core/src/worker/mod.rs, packages/apalis-cron/src/lib.rs, packages/apalis-redis/Cargo.toml, packages/apalis-redis/src/lib.rs, packages/apalis-redis/src/storage.rs, packages/apalis-sql/Cargo.toml, packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
Basically this allows workers to receive unstarted worker instance making it more useable eg  emit errors.
=> feat: allow backends to emit errors

Cargo.toml, examples/persisted-cron/Cargo.toml, examples/persisted-cron/src/main.rs, packages/apalis-core/src/memory.rs, packages/apalis-core/src/poller/mod.rs, packages/apalis-core/src/request.rs, packages/apalis-cron/src/lib.rs, packages/apalis-cron/src/pipe.rs
This feature allows you to quickly persist cron jobs guaranteeing they will be run and can be distributed!
=> Feat: Introduce simple ability to pipe cron jobs to any backend

Cargo.toml, examples/rest-api/Cargo.toml, examples/rest-api/src/main.rs, packages/apalis-core/src/backend.rs, packages/apalis-core/src/builder.rs, packages/apalis-core/src/codec/json.rs, packages/apalis-core/src/codec/mod.rs, packages/apalis-core/src/lib.rs, packages/apalis-core/src/memory.rs, packages/apalis-core/src/monitor/mod.rs, packages/apalis-core/src/request.rs, packages/apalis-core/src/worker/mod.rs, packages/apalis-cron/src/lib.rs, packages/apalis-cron/src/pipe.rs, packages/apalis-redis/src/expose.rs, packages/apalis-redis/src/lib.rs, packages/apalis-redis/src/storage.rs, packages/apalis-sql/src/context.rs, packages/apalis-sql/src/lib.rs, packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs, src/lib.rs
- Allows querying of backends
- Its Api agnostic, use it on actix, axum etc
=> feat: return of exposing backends to help in building apis

packages/apalis-redis/src/lib.rs
=> fix: re-export redis ConnectionManager & RedisError

packages/apalis-redis/src/storage.rs
Should fix #467
Improve test on reenque_orphaned
=> fix: reenque_orphaned for RedisStorage

.github/workflows/redis.yaml, packages/apalis-core/src/lib.rs, packages/apalis-core/src/worker/call_all.rs, packages/apalis-core/src/worker/mod.rs, packages/apalis-redis/src/storage.rs, packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
This PR enforces a few things:
1. Polling only happens when the service is ready
2. Polling does not happen when the worker is shutting down.
=> fix: allow polling only when worker is ready

examples/basics/Cargo.toml, examples/basics/src/main.rs, examples/catch-panic/Cargo.toml, examples/catch-panic/src/main.rs, examples/postgres/Cargo.toml, examples/postgres/src/main.rs
Add features to sql examples
Closes #476
=> chore: fix examples

packages/apalis-core/src/worker/mod.rs
=> fix: handle only the latest waker

packages/apalis-redis/src/storage.rs
As per title, without this change when redis restarts, it seems apalis get's stuck repeating this error over and over:
```
WARN  An error occurred during streaming jobs: An error was signalled by the server - ResponseError: user_script:15: consumer not registered script: e3ac73ae44f02d04176688b08c26ed751417cdb0, on @user_script:15.
```
After this change, on error `keep_alive()` will re-register, so it's fixed on the next call.
=> Add keep_alive() call when an error occurs in fetch_next(), to prevent permanent failure when redis restarts

packages/apalis-redis/src/storage.rs, packages/apalis-sql/src/mysql.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
This calls `reenqueue_orphaned` before starting to stream jobs.
This allows recovering your worker state. This logic will be improved in future releases but this is a quickfix for #504
=> fix: reenqueue oprphaned before starting streaming

Cargo.toml, examples/postgres/src/main.rs, examples/retries/Cargo.toml, examples/retries/src/main.rs, src/layers/retry/mod.rs, src/layers/tracing/make_span.rs
Integrates Retry Layer with the apalis inbuilt retry. Offers:
1. RetryPolicy
2. BackoffRetryPolicy
Resolves
- #268 
- #399
=> add: retry layer integration with task handling

.vscode/settings.json, CHANGELOG.md, packages/apalis-core/Cargo.toml, packages/apalis-core/src/builder.rs, packages/apalis-core/src/lib.rs, packages/apalis-core/src/monitor/mod.rs, packages/apalis-core/src/task/task_id.rs, packages/apalis-sql/src/sqlite.rs
- Removes some requirements for `apalis-core/default`
=> fix: ease apalis-core default features

CHANGELOG.md, packages/apalis-sql/migrations/postgres/20250404160441_cleanup_old_push_jobs_fn.sql
When i added priority support in https://github.com/geofmureithi/apalis/pull/533 I added a new `apalis.push_job` function for postgres because it had a new parameter, so the old one still exists, which causes problems if calling the function without specifying the priority to distinguish them. Dropping the old one will allow old calls to successfully call the new one. 
The issue should only be affecting calls to the function direclty in sql, not via the apalis library, as those do all specify priority.
Tested with a local project, the migration runs and calling the function as before works now.
=> fix: Add migration to drop old push_jobs function for postgres

CHANGELOG.md, packages/apalis-core/src/lib.rs
This PR removes the 2 second timeout on test execution.
This means the test user can set their own timeout.
=> fix(tests): avoid execute_next timeout

CHANGELOG.md, packages/apalis-sql/src/sqlite.rs
While implementing my own sqlite-based storage backend, I stumbled upon the following opportunities:
* No transactions for single queries
* no multi-statement query.
=> fix: improve sqlite queries with transactions and single statement queries

CHANGELOG.md, packages/apalis-sql/src/lib.rs, packages/apalis-sql/src/postgres.rs, packages/apalis-sql/src/sqlite.rs
I have fixed #539 by adding `to_timestamp` conversions on the postgres side. This is a good fix as long as the `done_at` etc. functions return `i64` instead of proper `DateTime` types on the Rust side.
I have added a test for this updating and one that exercises the `BackendExpose` implementation for postgres, both functions did not seem to be tested before. That also uncovered a timestamp-related bug in list_workers which I fixed here too.
Finally, I have added a changelog entry pointing to #539. Feel free to extend this pull request and/or squash-merge.
=> Fix #539 and add more postgres storage tests

CHANGELOG.md, packages/apalis-redis/lua/stats.lua
#506 introduced a bug when using `apalis-redis` with dragonfly DB: Since keys get programatically generated, in the for loop counting running jobs, the script does not work with dragonfly, which forbids using undeclared keys by default: https://www.dragonflydb.io/docs/managing-dragonfly/scripting#allowing-undeclared-keys .
With Redis, accessing undeclared keys is allowed, but considered a bad practice: https://redis.io/docs/latest/commands/eval/#:~:text=Important%3A%20to,in%20the%20database
A long-term fix would probably be something like storing a counter of running jobs somewhere, and pass the key of the counter to the script
=> fix(apalis-redis): enable "allow-undeclared-keys" for dragonflydb in `stats.lua`

CHANGELOG.md, packages/apalis-sql/src/sqlite.rs
Ensure that the function yields `None` when the ID list is empty, improving the handling of such cases in the SQLite fetch operation.
=> fix(sqlite): handle empty ID list in fetch_next to yield None, that make Event::Idle never trigger

CHANGELOG.md, examples/basics/src/main.rs, packages/apalis-core/src/response.rs
- This allows use of more error types like `BoxDynError` and `anyhow::Error`
Now you can do:
```rs
async fn send_email(task: Email) -> anyhow::Result<()> {
bail!("Email not sent")
}
```
Resolves #470
=> fix: ease the error type that is returned by a worker function
